/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class diskInfo */

#ifndef _Included_diskInfo
#define _Included_diskInfo
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     diskInfo
 * Method:    read
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_diskInfo_read
  (JNIEnv *, jobject);

/*
 * Class:     diskInfo
 * Method:    diskCount
 * Signature: ()I
 */
JNIEXPORT jint JNICALL Java_diskInfo_diskCount
  (JNIEnv *, jobject);

/*
 * Class:     diskInfo
 * Method:    getName
 * Signature: (I)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_diskInfo_getName
  (JNIEnv *, jobject, jint);

/*
 * Class:     diskInfo
 * Method:    getTotal
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_diskInfo_getTotal
  (JNIEnv *, jobject, jint);

/*
 * Class:     diskInfo
 * Method:    getUsed
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_diskInfo_getUsed
  (JNIEnv *, jobject, jint);

/*
 * Class:     diskInfo
 * Method:    getAvailable
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_diskInfo_getAvailable
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
